title: Hong-Yi Zhang
author:
  name: Hong-Yi Zhang
description: Theoretical Cosmology and Astroparticle Physics at Tsung-Dao Lee Institute

header_pages:
  - index.md
  - research.md
  - teaching.md
  - activities.md
  - blog.md
  - personal.md


# 中文站点基本信息和标题栏
title_zh: 张闳一
author_zh:
  name: 张闳一
description_zh: 李政道研究所 理论宇宙学和天体粒子物理

header_pages_zh:
  - zh/index.md


# Build settings
theme: minima
markdown: kramdown
url: "https://hongyi18.github.io"
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
lang: en

# Google Analytics and Google Search Console verification
google_analytics: G-H5XYXQSZCC
google_site_verification: J4ry5OJ-P85rCSorM016wikH5pYAFKODa5iT4lLw0OA


# Set to `true` to show excerpts on the homepage.
show_excerpts: true


# Set to `true` to show "Last updated on ..." in the footer.
show_update: true
