title: Hong-Yi Zhang
author:
  name: Hong-Yi Zhang


# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  Theoretical Cosmology and Astroparticle Physics at Tsung-Dao Lee Institute


header_pages:
  - index.md
  - research.md
  - teaching.md
  - activities.md
  - blog.md
  - personal.md


# Build settings
theme: minima
markdown: kramdown
plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-sitemap
# Google Analytics and Google Search Console verification
google_analytics: G-H5XYXQSZCC
google_site_verification: -i60Ta3JxYU-uD1dOb7nApfFwltbCUN6HBQQNBCfAoE


# Set to `true` to show excerpts on the homepage.
show_excerpts: true


# Set to `true` to show "Last updated on ..." in the footer.
show_update: true
