#!/bin/bash
#SBATCH --job-name=An_example_of_slurm
#SBATCH --partition=commons
#SBATCH --account=commons
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=40
#SBATCH --mem-per-cpu=2G
#SBATCH --time=24:00:00
#SBATCH --mail-user=myemail@rice.edu
#SBATCH --mail-type=ALL
#SBATCH --export=ALL

echo "My job was running on: "
echo $SLURM_NODELIST

module purge
module load GCC/9.3.0 OpenMPI/4.0.3 FFTW/3.3.8
./latticeeasy
